services:
  - type: web
    name: gestion-notas
    env: python
    buildCommand: ""
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
Create render.yaml for deployment
